apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort   # or LoadBalancer if using a cloud cluster
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500   # Optional; Kubernetes will pick one if not specified
